name: Docker Test & Publish

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Docker images
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 1. Собираем базовый образ (БЕЗ КЭША)
      - name: Build base image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          no-cache: true
          platforms: linux/amd64
          tags: ghcr.io/taffouxx/base:latest

      # 2. Собираем главное API (БЕЗ КЭША)
      - name: Publish API
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          no-cache: true
          platforms: linux/amd64
          file: crates/delta/Dockerfile
          tags: ghcr.io/taffouxx/api:latest
          build-args: |
            BASE_IMAGE=ghcr.io/taffouxx/base:latest

      # 3. Собираем Events
      - name: Publish Events
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          no-cache: true
          platforms: linux/amd64
          file: crates/bonfire/Dockerfile
          tags: ghcr.io/taffouxx/events:latest
          build-args: |
            BASE_IMAGE=ghcr.io/taffouxx/base:latest

      # 4. Собираем File Server
      - name: Publish File Server
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: crates/services/autumn/Dockerfile
          tags: ghcr.io/taffouxx/file-server:latest
          build-args: |
            BASE_IMAGE=ghcr.io/taffouxx/base:latest

      # 5. Собираем Proxy
      - name: Publish Proxy
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: crates/services/january/Dockerfile
          tags: ghcr.io/taffouxx/proxy:latest
          build-args: |
            BASE_IMAGE=ghcr.io/taffouxx/base:latest